export const CREATE_EMPLOYEE = 'CREATE_EMPLOYEE';

export const DELETE_EMPLOYEE = 'DELETE_EMPLOYEE';

export const GET_EMPLOYEE_BY_ID = 'GET_EMPLOYEE_BY_ID';

export const GET_LIST_EMPLOYEE = 'GET_LIST_EMPLOYEE';

export const REPAIR_EMPLOYEE = 'REPAIR_EMPLOYEE';

export const SHOW_ADD_FORM = 'SHOW_ADD_FORM';