
export const actionTodoList = {
    CREAT_TODOLIST: 'CREAT_TODOLIST',
    DELETE_TODOLIST: 'DELETE_TODOLIST',
    GET_TODOLIST: 'GET_TODOLIST',
    GET_LIST_TODOLIST: 'GET_LIST_TODOLIST',
    EDIT_TODOLIST: 'EDIT_TODOLIST',
};

